on: push
name: php-8.2-validate
jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: jeffwray/laravel-test-runner:8.2

    steps:
    - uses: actions/checkout@v1
    - run: goss --gossfile 8.2/goss.yaml validate
